//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mortgage_Loan_Processing_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public string PropertyType { get; set; }
        public string PropertyValue { get; set; }
        public string Expected_Loan_Amount { get; set; }
        public Nullable<int> LoanTenure { get; set; }
        public string DateOfApplication { get; set; }
        public string Aadhar { get; set; }
        public string Pan { get; set; }
        public string AccountNo { get; set; }
        public string username { get; set; }
        public string Status { get; set; }
        public string OtherDocuments { get; set; }
    }
}
