//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mortgage_Loan_Processing_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string name { get; set; }
        public string dateOfBirth { get; set; }
        public string contactNumber { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string Role { get; set; }
    }
}
